/* Database schema to keep the structure of entire database. */
CREATE DATABASE vet_clinic;

CREATE TABLE animals (
    id INT,
    name VARCHAR(100),
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL,
    PRIMARY KEY(id)
);

/* Vet clinic database: query and update animals table */
CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL,
    species VARCHAR(100),
    PRIMARY KEY(id)
);

/* Vet clinic database: query multiple tables */
CREATE TABLE owners (
  id SERIAL PRIMARY KEY,
  full_name VARCHAR(255),
  age INTEGER
);

CREATE TABLE species (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255)
);


BEGIN;

ALTER TABLE animals 
  DROP COLUMN species;

ALTER TABLE animals
  ADD COLUMN species_id INT REFERENCES species(id),
  ADD COLUMN owner_id INT REFERENCES owners(id);

COMMIT;

/* Vet clinic database: add "join table" for visits */


CREATE TABLE vets (
    id INTEGER SERIAL PRIMARY KEY,
    name VARCHAR(255),
    age INTEGER,
    date_of_graduation DATE
);


CREATE TABLE specializations (
    vet_id INT NOT NULL REFERENCES vets(id),
    species_id INT NOT NULL REFERENCES species(id),
    PRIMARY KEY(vet_id,species_id)
);


CREATE TABLE visits (
  animal_id INT NOT NULL,
  vet_id INT NOT NULL,
  visit_dates Date NOT NULL,
  CONSTRAINT primary_pk
  PRIMARY KEY (animal_id, vet_id, visit_dates),
  FOREIGN KEY (animal_id) REFERENCES animals (id),
  FOREIGN KEY (vet_id) REFERENCES vets (id)
);





